image/pxelinux.cfg/%: blobs/pxelinux.cfg/%
	mkdir -p image/pxelinux.cfg
	cp $< $@

image/extlinux/extlinux.conf: blobs/pxelinux.cfg/default-arm-rockchip
	mkdir -p image/extlinux
	cp $< $@

image-pxe: \
	image/pxelinux.cfg/default-arm-rockchip \
	image/pxelinux.cfg/default-arm-sunxi \
	image/extlinux/extlinux.conf
